#!/bin/sh
#Add by Jackie Xie

export TARGET_ROOT_DIR=$HOME/tmp/conf

if [ ! -d $HOME/tmp/conf ]; then \
   echo Create directory /var/conf ; \
   mkdir -p $HOME/tmp/conf ; \
fi

nvram show > $HOME/tmp/conf/nvram.config
